server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Progetto_distributori_V_0.1?currentSchema=v_0_1
    username: Vito
    password: vito
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
logging:
  file:
  path: "./logs"
  name: "./logs/gestore-be.log"
  # Logging pattern for the console
  pattern:
    console: "%-10(%d{HH:mm:ss.SSS} [%thread]) %-5level %logger{32} - %msg%n"
    # Logging pattern for file
    file: "%-10(%d{HH:mm:ss.SSS} [%thread]) %-5level %logger{32} - %msg%n"